### ISSUE TITLE
Reflection failed

### ISSUE THREAD

**Issue by SiroQ** [FlawlessNick/FlawlessNick#4]
[Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: java.lang.NoSuchFieldException: field_175196_v
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper.<init>(FlawlessNick.java:288)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.simplyrin.flawlessnick.FlawlessNick.<init>(FlawlessNick.java:61)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.Class.newInstance(Class.java:442)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:174)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:534)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:451)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:360)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraft.client.main.Main.main(Main.java:116)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[10:24:31] [Client thread/INFO] [STDERR]: [net.simplyrin.flawlessnick.FlawlessNick$FieldWrapper:<init>:291]: 	at GradleStart.main(GradleStart.java:26)

**Comment by SiroQ** [comment]
Only development
